
export OBJCOPY:=objcopy
export OBJCOPYFLAGS:=-I binary -O elf32-i386 -B i386
export BUILD:=build.sdl

all:
	@$(MAKE) --no-print-dir -C fonts

clean:
	@$(MAKE) --no-print-dir -C fonts clean

# vim: syntax=make
