# Top level Makefile for Nintendo DS.

ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif
export PATH		:=	$(DEVKITARM)/bin:$(PATH)
export TOPLEVEL := $(CURDIR)

VERSION=3.0


all:
	make -C lib -f Makefile.ds static

install:
	make -C lib -f Makefile.ds install-lib

uninstall:
	make -C lib -f Makefile.ds uninstall-lib

clean:
	make -C lib -f Makefile.ds clean

