
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include BoxLayout.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Button.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ButtonGroup.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include CheckBox.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ComboBox.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Component.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include EditableTextArea.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include FileParser.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Font.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include FontFactory.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ISO_8859_1.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Keyboard.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Language.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Link.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ParameterSet.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ProgressBar.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include RadioButton.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include RichTextArea.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ScrollBar.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ScrollPane.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include Stylus.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include TextArea.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include TextAreaFactory.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include TextContainer.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include TextField.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ToggleButton.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include WidgetColors.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include ZipFile.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include password_mask.cpp
 g++ -g -c -DZIPIT_Z2 -I ../include -I ../img -I ../../../libndspp/include string_utils.cpp
