#!/usr/bin/python

APPNAME="convertftf"

def set_options(opt):
    opt.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    conf.check_cfg(
        package='freetype2',
        mandatory=1,
        args='--cflags --libs')

def build(bld):
    bld.new_task_gen(features="cxx cprogram",
            source="main.cc file_wrapper.cc",
            uselib="FREETYPE2",
            target=APPNAME)
