#!/usr/bin/env python
# encoding: utf-8

def build(bld):
  #
  obj = bld.create_obj('cpp', 'shlib')
  obj.env = bld.env('sdl')
  obj.source = '''Main.cpp'''
  obj.target = '''cppunitmain'''

  # build subdirs
