#!/usr/bin/env python
# encoding: utf-8
import os
import Constants

def build(bld):
  #
  obj = bld.create_obj('cpp', 'staticlib')
  obj.env = bld.env('sdl').copy()
  obj.source = '''Main.cpp'''
  obj.target = '''cppunitmain'''

  # build subdirs
  #bld.add_subdirs('patch-test gui-test lang-test images sprite bwtimage parser')
  here = os.path.join(bld.env('sdl')['TOP'], 'tests')
  [bld.add_subdirs(d) for d in os.listdir(here)
      if os.path.exists(os.path.join(here,d,Constants.WSCRIPT_FILE))]
