#!/usr/bin/env python
# encoding: utf-8
import os
import Constants, Params

def build(bld):
  obj = bld.create_obj('cpp', 'staticlib')
  obj.inst_var = 0
  obj.env = bld.env('sdl').copy()
  obj.source = '''Main.cpp'''
  obj.target = '''cppunitmain'''

  # build subdirs
  here = os.path.join(Params.g_build.m_srcnode.abspath(), 'tests')
  [bld.add_subdirs(d) for d in os.listdir(here)
      if os.path.exists(os.path.join(here,d,Constants.WSCRIPT_FILE))]
