
export OBJCOPY:=objcopy
export OBJCOPYFLAGS:=-I binary -O elf32-i386 -B i386
export BUILD:=build.sdl

all:
	@$(MAKE) --no-print-dir -C img
	@$(MAKE) --no-print-dir -C builtin

clean:
	@$(MAKE) --no-print-dir -C img clean
	@$(MAKE) --no-print-dir -C builtin clean

# vim: syntax=make
