Import('bwtEnv')

# From images build the map, img, pal files
# Build the header
# Objcopy the binary files to .o files
# return the .o files to the parent SCon

imageFiles = ['checkbox.png', 'radiobutton.png']

objs = []
for img in imageFiles:
  bin = bwtEnv.Gfx2Bin( img )
  bwtEnv.Png2h( img )
  for b in bin:
    objs.append( bwtEnv.Bin2o(b))

Return('objs')
# vim: set filetype=python :
