
PREFIX=/usr/local

all: libunzip.a

clean:
	-rm *.o -f

install: libunzip.a
	cp -f libunzip.a $(PREFIX)/lib
	cp -f unzip.h ioapi.h $(PREFIX)/include

UNZ_OBJS = unzip.o ioapi.o

libunzip.a: $(UNZ_OBJS)
	ar rcv $@ $^

%.o:%.c
	gcc -o $@ $< -c
