Import ('testEnv mainObj')
env = testEnv.Copy()
files = env['TESTER_SOURCES']
o = env.Object(files)
o.append("""
    #build/pc/CookieJar.o
    #build/pc/Entity.o
    #build/pc/HeaderParser.o
    #build/pc/HtmlParser.o
    #build/pc/URI.o
    """.split())
tester = env.Program('tester', Flatten([mainObj, o]))
out = env.Test('test.passed', tester)
Return('out')
# vim: set filetype=python :
