#!/usr/bin/python

sources = '''
    sans.set
    sans.map
'''.split()

objects = []
for src in sources:
    tgt = src+'_o'
    bin = src+'.bin'
    bld.new_task_gen(
        features='copy',
        source=src,
        target=bin)
    bld.objcopy(bin, target=tgt)
    objects.append(tgt)

bld.new_task_gen(
    features='cc cstaticlib', target='vera',
    add_objects=objects,
    export_incdirs='.')

bld.new_task_gen(
    features='name2h',
    target='sans.h',
    source=(src+'.bin' for src in sources))
