Import ('env')
import os.path

# copy the env since we change it by adding the font path
testEnv = env.Clone()
testEnv.Append(CPPPATH='fonts')

# get the build target (pc, arm9, arm7) and the source dir (arm9 or 7)
buildTarget =  testEnv['PLATFORM_NAME']
sourceDirectory = testEnv['SOURCE_NAME']
output = None
if (buildTarget != 'arm7'):
  # find out the program name (based on this directory's name)
  programName = os.path.basename(str(Dir('.').abspath))
  Export('testEnv')
  # create the font files
  objs = SConscript('common/fonts/SConscript', build_dir='fonts', duplicate=0)
  program = testEnv.Program( '%s/%s'%(sourceDirectory, programName), [ '%s/%s'%(sourceDirectory, 'main.cpp') , objs])
  if (buildTarget != 'pc'):
    env.SideEffect(str(program[0])+'.map', program)
    env.Elf2Arm('%s.arm'%str(program[0]),  program)

  # only create the .nds for the arm9 build target
  if (buildTarget == 'arm9'):
    #arm7PN = '/arm7/%s'%programName
    arm9PN = '/arm9/%s'%programName
    #nds = testEnv.NdsTool( programName, ['#/build%s.arm'%(2*arm7PN), '#/build%s.arm'%(2*arm9PN,)])
    nds = testEnv.NdsTool( programName, ['#/build%s.arm'%(2*arm9PN)])
    output = testEnv.Command( '/'.join([ str(Dir('.').srcnode().abspath), programName+'.nds' ]),
                   nds,
                   [Copy('$TARGET', '$SOURCE')]
                   )
env.Alias(programName, output)

# vim: set filetype=python :
