#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

include $(DEVKITARM)/ds_rules

#---------------------------------------------------------------------------------
BUILD		:= build

ARM9SOURCES :=	source/common

DATESTRING	:=	$(shell date +%Y)$(shell date +%m)$(shell date +%d)

export PATH		:=	$(DEVKITARM)/bin:$(PATH)

export BASEDIR	:=	$(CURDIR)
export LIBDIR	:=	$(BASEDIR)/lib
export DEPENDS	:=	$(BASEDIR)/deps
export INCDIR	:=	$(BASEDIR)/include
export BUILDDIR	:=	$(BASEDIR)/$(BUILD)

ARM9CFILES	:=	$(foreach dir,$(ARM9SOURCES),$(notdir $(wildcard $(dir)/*.c)))
ARM9CPPFILES	:=	$(foreach dir,$(ARM9SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
ARM9SFILES	:=	$(foreach dir,$(ARM9SOURCES),$(notdir $(wildcard $(dir)/*.s)))
ARM9BINFILES	:=	$(foreach dir,$(ARM9SOURCES),$(notdir $(wildcard $(dir)/*.bin)))


export ARM9_VPATH	:=	$(foreach dir,$(ARM9SOURCES),$(BASEDIR)/$(dir))

export ARM9OBJS :=	$(ARM9BINFILES:.bin=.o) $(ARM9CFILES:.c=.o) $(ARM9SFILES:.s=.o) $(ARM9CPPFILES:.cpp=.o)
export ARM9INC	:=	-I$(BASEDIR)/source/common -I$(LIBNDS)/include -I$(LIBNDSPP)/include \
			-I$(BASEDIR)/common/img

export ARCH	:=	-mthumb -mthumb-interwork

export ARM9FLAGS	:=	$(ARCH) -march=armv5te -mtune=arm946e-s -DARM9

export BASEFLAGS	:=	-g -Wall -O2\
				-fomit-frame-pointer\
				-ffast-math \
				-I$(INCDIR)


.PHONY:	all libs dist docs

#---------------------------------------------------------------------------------
all:	$(DEPENDS)/arm9 lib $(BUILD)/arm9
#---------------------------------------------------------------------------------
	@$(MAKE) -C $(BASEDIR)/common -f Makefile
	@$(MAKE) -C $(BUILD)/arm9 -f $(BASEDIR)/Makefile.arm9

$(BUILD)/arm9:
#---------------------------------------------------------------------------------
	mkdir -p $@
#---------------------------------------------------------------------------------
$(DEPENDS)/arm9:
#---------------------------------------------------------------------------------
	mkdir -p $@/arm9

#---------------------------------------------------------------------------------
lib:
#---------------------------------------------------------------------------------
	mkdir -p lib

#---------------------------------------------------------------------------------
clean:
#---------------------------------------------------------------------------------
	rm -fr $(DEPENDS) $(BUILD) *.bz2

#---------------------------------------------------------------------------------
dist: all
#---------------------------------------------------------------------------------
	@tar --exclude=*CVS* -cvjf libbwt-src-$(DATESTRING).tar.bz2 source include license.txt Makefile*
	@tar --exclude=*CVS* -cvjf libbwt-$(DATESTRING).tar.bz2 include lib license.txt

#---------------------------------------------------------------------------------
install: dist
#---------------------------------------------------------------------------------
	mkdir -p $(DEVKITPRO)/libbwt
	bzip2 -cd libndspp-$(DATESTRING).tar.bz2 | tar -xv -C $(DEVKITPRO)/libndspp

#---------------------------------------------------------------------------------
docs:
#---------------------------------------------------------------------------------
	doxygen libndspp.doxy.cfg

