import glob, os.path
Import('env')

# Build the bwt library.

# New Environment from parent.
bwtEnv = env.Copy()

# make sure we search for headers in img dir
bwtEnv.Append(CPPPATH='../data')

Export('bwtEnv')
# build common source into "common" build dir
objs = SConscript('source/SConscript', build_dir='common', duplicate=0)
# build image files into "data" build dir
objs.append(SConscript('img/SConscript', build_dir='data', duplicate=0))

# build the library in lib dir.
libbwt = bwtEnv.Library('lib/bwt', objs)

# return the library to the parent.
Return('libbwt')

# vim: set filetype=python :
