#!/usr/bin/python
images = bld.glob('img/*.png')
bld.transform_image(images,
    GRITFLAGS='-pw 16 -gB 8 -m! -ftc -fh -q -pe64'.split())

bld.new_task_gen(features='cc', target='img_objects',
    source=(i.replace('.png', '.c') for i in images))

lib = bld.static_library('bwt', 'source',
        uselib_local='ndspp', add_objects='img_objects')
lib.include_directories('include img')
