Import ('testEnv mainObj')
env = testEnv.Copy()
files = env['TESTER_SOURCES']
o = env.Object(files)
o.append("""
    #build/pc/CookieJar.o
    #build/pc/ElementFactory.o
    #build/pc/Entity.o
    #build/pc/HeaderParser.o
    #build/pc/HtmlAnchorElement.o
    #build/pc/HtmlBodyElement.o
    #build/pc/HtmlBlockElement.o
    #build/pc/HtmlConstants.o
    #build/pc/HtmlDocument.o
    #build/pc/HtmlElement.o
    #build/pc/HtmlFormElement.o
    #build/pc/HtmlImageElement.o
    #build/pc/HtmlInputElement.o
    #build/pc/HtmlMetaElement.o
    #build/pc/HtmlOptionElement.o
    #build/pc/HtmlParser.o
    #build/pc/HtmlPreElement.o
    #build/pc/HtmlTextAreaElement.o
    #build/pc/URI.o
    """.split())
tester = env.Program('tester', Flatten([mainObj, o]))
out = env.Test('test.passed', tester)
Return('out')
# vim: set filetype=python :
