See the file ../bunjalloo/BUILD for full instructions.

For the impatient, run this command:

  ./configure

...and keep installing dependencies until it works. Once done, you have to run
this command:

  make install

This will build and "install" the libraries to the lib directory. Now go and do
the something similar in ../bunjalloo.
