-include $(DEVKITARM)/base_rules

CFLAGS	:=	$(BASEFLAGS) $(ARM7FLAGS) $(ARM7INC)
CXXFLAGS       :=      $(CFLAGS) -fno-rtti -fno-exceptions
ASFLAGS :=	$(ARM7FLAGS)
VPATH	:=	$(ARM7_VPATH)
DEPSDIR	:=	$(DEPENDS)/arm7

$(LIBDIR)/libndspp7.a:	$(ARM7OBJS)

-include $(DEPSDIR)/*.d
