-include $(DEVKITARM)/base_rules

CFLAGS	:=	$(BASEFLAGS) $(ARM9FLAGS) $(ARM9INC)
CXXFLAGS       :=      $(CFLAGS) -fno-rtti -fno-exceptions -Wno-strict-aliasing
ASFLAGS :=	$(ARM9FLAGS)
VPATH	:=	$(ARM9_VPATH)
DEPSDIR	:=	$(DEPENDS)/arm9

$(LIBDIR)/libndspp9.a:	$(ARM9OBJS)

-include $(DEPSDIR)/*.d

%.o	:	%.bin
	@echo $(notdir $<)
	@$(bin2o)
