#!/usr/bin/env python
# encoding: utf-8

import Params, Environment
import os, os.path
import sys

top = os.getcwd()
VERSION="0.1"

srcdir='.'
blddir='bld'
waf_tools="waf_tools"
sys.path.append(waf_tools)

def set_options(opt):
  opt.tool_options('g++')
  opt.tool_options('compiler_cxx')

def arm_tool_check(conf):
  conf.check_tool('compiler_cxx')

  # cannot check compiler_cc for devkitArm as it needs LINKFLAGS, which waf
  # stips off in the check.
  conf.check_tool('arm7', waf_tools)
  conf.check_tool('arm9', waf_tools)
  conf.check_tool('ndstool', waf_tools)
  conf.check_tool('objcopy', waf_tools)

def header_check(conf):
  # check headers
  e = conf.create_header_configurator()
  e.mandatory = 1
  e.nosystem = 1
  e.uselib = 'ARM9'
  e.path = conf.env['CPPPATH_ARM9']
  for header in ('fat.h', 'png.h', 'zlib.h', 'gif_lib.h', 'matrixSsl.h'):
    e.name = header
    e.nosystem = 1
    e.run()
  e.name = 'dswifi9.h'
  e.header_code = '#include <nds/jtypes.h>'
  e.run()

  e.name = 'jpeglib.h'
  e.header_code = '#include <stdio.h>'
  e.run()

def configure(conf):
  # check native compiler
  arm_tool_check(conf)
  header_check(conf)

  sdl = Environment.Environment()
  conf.set_env_name('sdl', sdl)
  sdl.set_variant('sdl')
  conf.setenv('sdl')
  conf.check_tool('compiler_cxx')

def build(bld):
  # overcome chdir problems for jump-to-error
  if not Params.g_commands['clean']:
    print "waf: Entering directory `%s'"%(top+"/"+blddir)
  # process subfolders from here
  arm9obj = bld.create_obj('cpp', 'staticlib')
  arm9obj.includes = 'include source/common'
  arm7obj = arm9obj.clone('default')

  sdl = arm9obj.clone('sdl')
  arm9obj.includes += ' source/arm9'
  arm7obj.includes += ' source/arm7'
  sdl.includes += ' source/pc'

  arm9obj.find_sources_in_dirs('source/arm9 source/common')
  arm7obj.find_sources_in_dirs('source/arm7')
  arm7obj.uselib = 'ARM7'
  arm9obj.uselib = 'ARM9'
  arm9obj.target = 'ndspp-arm9'
  arm7obj.target = 'ndspp-arm7'
  sdl.target = 'ndspp-pc'
  sdl.find_sources_in_dirs('source/pc source/common')

