#!/usr/bin/python

bld.transform_image('source/common/minimessage_data.png',
    GRITFLAGS='-pw 16 -gB 4 -m! -ftc -fh -q -pe2 -pT 1'.split())

bld.new_task_gen(features='cc',
    target='minimessage_data',
    source='source/common/minimessage_data.c')

lib = bld.static_library('ndspp', 'source/common',
        install_path=0,
        add_objects='minimessage_data')
lib.include_directories('include')

if bld.env.variant().startswith('nds'):
    lib.source_directories('source/arm9')
else:
    lib.source_directories('source/pc')
