#!/usr/bin/python
import Options
blddir = '_build_'
def set_options(opt):
    opt.tool_options('pytest', tooldir='.')

def configure(conf):
    conf.check_tool('pytest', tooldir='.')

def build(bld):
    test = getattr(Options.options, 'test')
    if not test:
        test = 'test_*.py'
    bld.new_task_gen(source=bld.glob(test))
